name: Create and Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.3.42)'
        required: false
        type: string
      prerelease:
        description: 'Mark as a pre-release'
        required: true
        type: boolean
        default: false
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-installers:
    name: Create Installers for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64

    steps:
    - name: Set Version from Project File (if not provided)
      id: set_version
      shell: bash
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          VERSION=$(grep -oP '<Version>\K[^<]+' xk/xk.csproj)
          echo "Using version from xk.csproj: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
        fi

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-${{ matrix.runtime }}-${{ env.version }}
        path: ./publish

    - name: Create Windows Installer
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        dotnet tool install --global wix --version 5.0.1
        $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
        wix heat dir ./publish -cg PublishedFiles -gg -sfrag -dr INSTALLFOLDER -out harvested.wxs

        $wxsContent = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Wix xmlns=\"http://wixtoolset.org/schemas/v4/wxs\">\n  <Package Name=\"XferKit\" Language=\"1033\" Version=\"${{ env.version }}\" Manufacturer=\"Parks Computing\" UpgradeCode=\"A1B2C3D4-E5F6-7890-ABCD-123456789012\">\n    <MajorUpgrade DowngradeErrorMessage=\"A newer version is already installed.\"/>\n    <MediaTemplate EmbedCab=\"yes\"/>\n    <Feature Id=\"ProductFeature\" Title=\"XferKit\" Level=\"1\">\n      <ComponentGroupRef Id=\"PublishedFiles\"/>\n    </Feature>\n  </Package>\n</Wix>"
        $wxsContent | Out-File -FilePath "Product.wxs" -Encoding UTF8
        wix build Product.wxs harvested.wxs -arch x64 -out "./xk-${{ env.version }}-installer-win-x64.msi"

    - name: Upload Windows Installer
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: installer-win-x64
        path: ./xk-${{ env.version }}-installer-win-x64.msi

    - name: Create Linux Debian Package
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        mkdir -p debian/DEBIAN debian/usr/local/bin
        cp -r publish/* debian/usr/local/bin/
        chmod +x debian/usr/local/bin/xk
        cat > debian/DEBIAN/control << EOF
        Package: xferkit
        Version: ${{ env.version }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Parks Computing <support@parkscomputing.com>
        Description: XferKit - API Management CLI Tool.
        EOF
        dpkg-deb --build debian "./xk-${{ env.version }}-installer-linux-x64.deb"

    - name: Upload Linux Installer
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: installer-linux-x64
        path: ./xk-${{ env.version }}-installer-linux-x64.deb

    - name: Create macOS Package
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        pkgbuild --root ./publish --identifier com.parkscomputing.xferkit \
                 --version ${{ env.version }} \
                 "./xk-${{ env.version }}-installer-osx-x64.pkg"

    - name: Upload macOS Installer
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: installer-osx-x64
        path: ./xk-${{ env.version }}-installer-osx-x64.pkg

  publish-release:
    name: Publish GitHub Release
    needs: create-installers
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-assets

    - name: List release assets
      run: ls -lR release-assets

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.version }}
        name: XferKit v${{ env.version }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        files: release-assets/*
